move_and_grasp_plug:
  arm: l
  ik_node_name: plugs_ik_node
  plug_frame: plug_frame_base_filtered
  use_preferred_grip_orientation: false
  grip_angle_offset: 0.24
  pose_suggestion:
    shoulder_pan: 1.24
    shoulder_lift: 1.02
    upper_arm_roll: 2.56
    elbow_flex: -1.79
    forearm_roll: 1.51
    wrist_flex: -0.334
    wrist_roll: 4.59
