detect_plug_on_base:
  arm: 'l'
  arm_controller: l_arm_plugs_controller
  max_speed: 0.8
  n_samples: 1
  target_pose:
    joint_names: 'shoulder_pan shoulder_lift upper_arm_roll elbow_flex forearm_roll wrist_flex wrist_roll'    
    shoulder_pan:   0.59476926989195278
    shoulder_lift:  -0.011825403485909367
    upper_arm_roll: 1.6411891210921308
    elbow_flex:     -2.0984196948409162
    forearm_roll:   1.2475684529735878
    wrist_flex:     -0.49435426804043425
    wrist_roll:     3.5351127383767049  




